server:
  port: 3344

spring:
  application:
    name:  tdtk-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaogaoyanjiu/springcloud-config.git #GitHub上面的git仓库名字